// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyScopes     = "apiKey.Scopes"
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Actor defines model for Actor.
type Actor struct {
	OrgMsp string `json:"orgMsp"`
	UserId string `json:"userId"`
}

// CreateBusinessDataRequest defines model for CreateBusinessDataRequest.
type CreateBusinessDataRequest struct {
	// BusinessData Arbitrary JSON data
	BusinessData map[string]interface{} `json:"businessData"`
	RecordId     string                 `json:"recordId"`
}

// CreateInvoiceRequest defines model for CreateInvoiceRequest.
type CreateInvoiceRequest struct {
	Filename string `json:"filename"`
	RecordId string `json:"recordId"`

	// XmlBase64 Base64 encoded XML content
	XmlBase64 string `json:"xmlBase64"`
}

// Error defines model for Error.
type Error struct {
	Code    *int    `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// HistoryEntry defines model for HistoryEntry.
type HistoryEntry struct {
	IsDelete  *bool         `json:"isDelete,omitempty"`
	Timestamp *time.Time    `json:"timestamp,omitempty"`
	TxId      *string       `json:"txId,omitempty"`
	Value     *LedgerRecord `json:"value,omitempty"`
}

// LedgerRecord defines model for LedgerRecord.
type LedgerRecord struct {
	Actor Actor `json:"actor"`

	// BusinessData Can be generic JSON or InvoiceData structure
	BusinessData  *map[string]interface{} `json:"businessData,omitempty"`
	CreatedAt     *time.Time              `json:"createdAt,omitempty"`
	DocType       *string                 `json:"docType,omitempty"`
	LockPolicyId  *string                 `json:"lockPolicyId,omitempty"`
	Locked        *bool                   `json:"locked,omitempty"`
	LockedAt      *string                 `json:"lockedAt,omitempty"`
	PolicyVersion *int                    `json:"policyVersion,omitempty"`
	RecordId      string                  `json:"recordId"`
	Status        Status                  `json:"status"`
}

// PaginatedResponse defines model for PaginatedResponse.
type PaginatedResponse struct {
	// Bookmark The marker for the next page of results. Pass this in the next request to fetch the next page.
	Bookmark *string        `json:"bookmark,omitempty"`
	Records  []LedgerRecord `json:"records"`

	// RecordsCount The number of records returned in this batch
	RecordsCount int `json:"recordsCount"`
}

// RecordResponse defines model for RecordResponse.
type RecordResponse struct {
	Data LedgerRecord `json:"data"`

	// History Only populated if includeHistory=true
	History *[]HistoryEntry `json:"history,omitempty"`
}

// Status defines model for Status.
type Status struct {
	Code      string     `json:"code"`
	Note      *string    `json:"note,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// UpdateBusinessDataRequest defines model for UpdateBusinessDataRequest.
type UpdateBusinessDataRequest struct {
	// BusinessData The new business data to replace the existing data
	BusinessData map[string]interface{} `json:"businessData"`
}

// UpdateInvoiceRequest defines model for UpdateInvoiceRequest.
type UpdateInvoiceRequest struct {
	NewFilename  string `json:"newFilename"`
	NewXmlBase64 string `json:"newXmlBase64"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// NotAcceptable defines model for NotAcceptable.
type NotAcceptable = Error

// NotFound defines model for NotFound.
type NotFound = Error

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// UnsupportedMediaType defines model for UnsupportedMediaType.
type UnsupportedMediaType = Error

// GetRecordsByDateRangeParams defines parameters for GetRecordsByDateRange.
type GetRecordsByDateRangeParams struct {
	// Start Start date (RFC3339 format, e.g., 2023-01-01T00:00:00Z)
	Start time.Time `form:"start" json:"start"`

	// End End date (RFC3339 format)
	End time.Time `form:"end" json:"end"`

	// PageSize Number of records to return per page (default 10)
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`

	// Bookmark Bookmark for the next page of results
	Bookmark *string `form:"bookmark,omitempty" json:"bookmark,omitempty"`
}

// GetRecordParams defines parameters for GetRecord.
type GetRecordParams struct {
	IncludeHistory *bool `form:"includeHistory,omitempty" json:"includeHistory,omitempty"`
}

// CreateBusinessDataRecordJSONRequestBody defines body for CreateBusinessDataRecord for application/json ContentType.
type CreateBusinessDataRecordJSONRequestBody = CreateBusinessDataRequest

// CreateInvoiceRecordJSONRequestBody defines body for CreateInvoiceRecord for application/json ContentType.
type CreateInvoiceRecordJSONRequestBody = CreateInvoiceRequest

// UpdateBusinessDataJSONRequestBody defines body for UpdateBusinessData for application/json ContentType.
type UpdateBusinessDataJSONRequestBody = UpdateBusinessDataRequest

// UpdateInvoiceRecordJSONRequestBody defines body for UpdateInvoiceRecord for application/json ContentType.
type UpdateInvoiceRecordJSONRequestBody = UpdateInvoiceRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Health check
	// (GET /health)
	CheckHealth(w http.ResponseWriter, r *http.Request)
	// Search records by date range
	// (GET /records)
	GetRecordsByDateRange(w http.ResponseWriter, r *http.Request, params GetRecordsByDateRangeParams)
	// Create a record with generic business data
	// (POST /records/business-data)
	CreateBusinessDataRecord(w http.ResponseWriter, r *http.Request)
	// Create an Invoice record
	// (POST /records/invoice)
	CreateInvoiceRecord(w http.ResponseWriter, r *http.Request)
	// Get a ledger record (with optional history)
	// (GET /records/{recordId})
	GetRecord(w http.ResponseWriter, r *http.Request, recordId string, params GetRecordParams)
	// Update business data of a generic record
	// (PUT /records/{recordId}/business-data)
	UpdateBusinessData(w http.ResponseWriter, r *http.Request, recordId string)
	// Update an existing Invoice record
	// (PUT /records/{recordId}/invoice)
	UpdateInvoiceRecord(w http.ResponseWriter, r *http.Request, recordId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Health check
// (GET /health)
func (_ Unimplemented) CheckHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Search records by date range
// (GET /records)
func (_ Unimplemented) GetRecordsByDateRange(w http.ResponseWriter, r *http.Request, params GetRecordsByDateRangeParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a record with generic business data
// (POST /records/business-data)
func (_ Unimplemented) CreateBusinessDataRecord(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create an Invoice record
// (POST /records/invoice)
func (_ Unimplemented) CreateInvoiceRecord(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a ledger record (with optional history)
// (GET /records/{recordId})
func (_ Unimplemented) GetRecord(w http.ResponseWriter, r *http.Request, recordId string, params GetRecordParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update business data of a generic record
// (PUT /records/{recordId}/business-data)
func (_ Unimplemented) UpdateBusinessData(w http.ResponseWriter, r *http.Request, recordId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an existing Invoice record
// (PUT /records/{recordId}/invoice)
func (_ Unimplemented) UpdateInvoiceRecord(w http.ResponseWriter, r *http.Request, recordId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CheckHealth operation middleware
func (siw *ServerInterfaceWrapper) CheckHealth(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CheckHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetRecordsByDateRange operation middleware
func (siw *ServerInterfaceWrapper) GetRecordsByDateRange(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRecordsByDateRangeParams

	// ------------- Required query parameter "start" -------------

	if paramValue := r.URL.Query().Get("start"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "start"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "start", r.URL.Query(), &params.Start)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "start", Err: err})
		return
	}

	// ------------- Required query parameter "end" -------------

	if paramValue := r.URL.Query().Get("end"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "end"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "end", r.URL.Query(), &params.End)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "end", Err: err})
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		return
	}

	// ------------- Optional query parameter "bookmark" -------------

	err = runtime.BindQueryParameter("form", true, false, "bookmark", r.URL.Query(), &params.Bookmark)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bookmark", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRecordsByDateRange(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateBusinessDataRecord operation middleware
func (siw *ServerInterfaceWrapper) CreateBusinessDataRecord(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateBusinessDataRecord(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateInvoiceRecord operation middleware
func (siw *ServerInterfaceWrapper) CreateInvoiceRecord(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateInvoiceRecord(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetRecord operation middleware
func (siw *ServerInterfaceWrapper) GetRecord(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "recordId" -------------
	var recordId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "recordId", runtime.ParamLocationPath, chi.URLParam(r, "recordId"), &recordId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recordId", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRecordParams

	// ------------- Optional query parameter "includeHistory" -------------

	err = runtime.BindQueryParameter("form", true, false, "includeHistory", r.URL.Query(), &params.IncludeHistory)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "includeHistory", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRecord(w, r, recordId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UpdateBusinessData operation middleware
func (siw *ServerInterfaceWrapper) UpdateBusinessData(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "recordId" -------------
	var recordId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "recordId", runtime.ParamLocationPath, chi.URLParam(r, "recordId"), &recordId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recordId", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateBusinessData(w, r, recordId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UpdateInvoiceRecord operation middleware
func (siw *ServerInterfaceWrapper) UpdateInvoiceRecord(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "recordId" -------------
	var recordId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "recordId", runtime.ParamLocationPath, chi.URLParam(r, "recordId"), &recordId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recordId", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateInvoiceRecord(w, r, recordId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.CheckHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/records", wrapper.GetRecordsByDateRange)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/records/business-data", wrapper.CreateBusinessDataRecord)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/records/invoice", wrapper.CreateInvoiceRecord)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/records/{recordId}", wrapper.GetRecord)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/records/{recordId}/business-data", wrapper.UpdateBusinessData)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/records/{recordId}/invoice", wrapper.UpdateInvoiceRecord)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xb/VPbOPP/VzT63g9wOMEJoQOZ6fQb3q5cC5cB+nKQPDeKvUlEbcmVZCCl+d+fkWQb",
	"27F5aYGnnetMZ4Jje7W72v3sZ1fpNfZ4GHEGTEncvcYCZMSZBHOxRfwj+ByDVPrK40wBM3+SKAqoRxTl",
	"bPVccqa/k94UQqL/+k3AGHfx/63eiF61d+XqrhBc4Pl87mAfpCdopIXgrl4LJYuhpX12QQLqI8qiWC3j",
	"uYP3uBhR3wf29JpkS6GlI/C48FHAvU/gIy5QBCKkUlLOkA+Mgm+U22cKBCPBMYgLEFbwk6uZLorsqih5",
	"0MGHXPU8DyJFRgE8vR6HXKHcelaBPR4z/+nXPgLJY+EBYlyhsVlz7uATzg8ImyXRJJ9ejRPOkV4RZUvO",
	"HfyOkVhNuaBf4Bk8kV8NLR3oGGUTHbE0TSUfmKJqtmx1k3EUcaHAPwCfkpNZBM+hY7YqMssis65+MHlX",
	"i+55yqYP8X2q3yRBX/AIhKIalcYkkODgKPfVNeZiciAj/VdIrt4Cm6gp7q61HRxSll62HBwRpXMGd/F/",
	"zkjjS69x6jY2hyu/YQcr4wEslaBsol0USxD7fknki869RP5/859Gpdi5gwV8jqnQIXGWqp0tNsxe4KNz",
	"8JTWY1sAUbAVS8pAyh2iSA6SH+CiUU5C/atKxFDetp4YUSWImKE/j/86RL4W4GC4ImFk8UVOaRQCU9pd",
	"+Ph1Y3MTO/gS6GSqcHfddecVZgmDrNbBmSh8tLvdcN0Wdr7B6fdzebauU/RIvev32QWnHnyb18c0AEZC",
	"KJpJrcjmVRgUTW2vr99m62Bw6QwGsjFcGQyaZ73GKWl8GV6vOZ15ZQhX+3j/8H2j7bbXHtvRDr4Kgy0i",
	"4UVHL1iu7vp7BMzjPvjo48FblGJNLpRwf2ezM/pwOfHD9zOvHVyMzl16cNy53D/fWNk+v4pG7PSCfDgM",
	"+hM+2d+5ik53OlcH5wcbb9vBp/6E68/YDzejv9vvVoq2rbc77Y0N9xYDl151E5e6jc2V1eF1Z778+8KX",
	"7fnLl1+LX63NXy6/elDkZVGR91lVBGZU4gEhpz1c2PGO62aiKVMwAUMTQpCSTEqRmRIvk+ljLkKiSn7U",
	"wnJea9bk3IIpr6lUXMx2mRKzB1pE5Q4EoIyqidwR5wEQpgUrGoJUJDTwn6jcxT5R0NC3iuqvFbUfDPzr",
	"zryhP9rpx4n96BY+ll51B4PmYOCvLL9aetU9/Xq20hgWnliuTAl1dVcN0ZfFNBv3Gnu6Ll2/qMnrCxLE",
	"cFcVfgv+BIQlsNU7UnjiYTtC0hp9mwa2kM+d7yg924ShEaAJMBDUs1HJBUogWctDUonYU7EAXGGiZxDc",
	"76kfIDYEEP8vFsxSSxe21edeysNuErKwSU6Z3izis4XmO9fSHU2fB9SbVcbnw3DftkfV2Wnv2Q2o9/Vv",
	"X58+FSNj7nsQklo2uwiJ+YL5iHVRKqJieVe6HNunbikbaYA4Sf5lkqtKR59MKNPBf5R09A/li5x/Con4",
	"tFjLT6aA9B0QukIgNQXE4EqhiEwA8TESIONAySbqEymRmlKJKLt5TCRNvuJoDMqbFgU0C3xg0ur1er2t",
	"ZrNZz29siVAQyodBYiaQCEFmOXnbPLYt0KLZLA5HIKyR5lkkQMWCgW9NpBKNiPKmeSNaFdW3co8lLqlQ",
	"ta1W+/yeFrfNTzD2IX6Y2tK8aLKGEBTxKA50ICE6RpR5QexDUsxfanTBzv28XyAAC94vecSv4+THWS59",
	"DyXC20e7vZPdnUVErc/zXuP0n5oEZ9ySkzKTz/Ok36u7zMj/YQrU7fTV+LBqR94ZE/6XDarJTLhEqQTT",
	"omp8ERAFxAODMHBFpaJskvavJTtK1t7ZG1qrv6s3ZHC5l2sPn6wNZHD5Md+Z/VBdUd4JJVWHVZskwYsF",
	"VbNjjSoJGY3oG6hAr15/H72BGerFagpMJcMsXUmovj0F4oMuonYD8MdGr7/feLP7943OiWRNYYEIEFqS",
	"CVVztZem658fTnA5Jv/8cGIW5oJ+Mesiux6KzWBOR+SWkYIMPpq6Z//S/MncudFjqlRkB2qUjXm1pboU",
	"h4Tpqj9BgUH4rEhdUjVFMgKPjqmHkiGceSMJYIkI89EfCc1Ocxnp6DeVl6ocGUV9wfkY9fr72MEXKZ/C",
	"rabbdLWveASMRBR38VrTba5hE09Ts1WrUyCB9eEETL7ohDD+McOj7Sl4n17bZ5ziWUTbdR80oXxAIt7w",
	"s5sC8a5fxN6Wu1ANhvdrfRfnoHq7qETWFya8Ou3NuvKZOWG1PNY2csckDtTd71adUJh0isOQ6NKPrdeR",
	"p3fA3FrN0atks8rDdyUoXOjg0dTNsk0UUKnyBClpwUwMJjQwiUTwNRYDEoRZ3leMhT9AWYoit2Y7RMGR",
	"fswEkyAhKBASd8/KOh0rIpQVu3S0t722traZjDEcBM1J00F29NVquK0T1+2af6fLKSZ8jkHMbiBBamk4",
	"D1i2/NxEWWXJfs4aXXbALvMrza8zEZj/cxl4uEDBTaHXLBxFIGwXspQkBmq5dYbr547pF8B5a7N80uke",
	"kisaxqG+sBUyuaqi8wvzzqR7urVDqtEs67zymlV3nM3GsIpXzoffCZ638fjFxrLyYC5rjwxG+EjGngdS",
	"juMgsJBnVbodtnIH0OaV1t2vFI7dzEtrd790c7r8HWC8fh+LKoH4UYH8GIjwpll2jGY5lC0A+2pKchtp",
	"0xhxWYHz9hhEo7wm2QVqYYb4hDLNOcjiMdEiqFedZiWjrWQusMX92aPFav3h2bxIRDXszReSpvVoipSm",
	"sTX5khXLnyhZ3Bd3v1H8RYJ5a/M5fhxgfEoCAcSf2QbQJGqntX4f11Qckf/86GAzApE0gU1rkM7XCw10",
	"ESuSI8tvQ4m09SBBMDMVUSouDGYwcxSYnofWwEXWZT85UpT6+R8MJBLtMuz9BRa/wOJZwIKhYugVoeE6",
	"PaKY1/b1WS+32L8ZBhwR0/AnBDh35FHfmFQ0ClVkujiwrib7yVCgfHj1pCy6NMevj8jkV22FffkDFCIl",
	"jF0ySM4jO/NAyUx/uW6rKshfXLFxi8Pdx9vBx/uJz/BpakL9ZPtehcF9bvaYHCb8VAWhc6+CsJf+tPMb",
	"K8i/GMNtEJfORvgYkYz13Y7pBeZXDxFljvbvwohv4Y3us/PGX/jwCx/q8IGwmxPSBbKXO3cz2Zw/DTsb",
	"auqVnsGdDXWiSbNa1Xz+LfdIgHbgAgJufjOc/u+FpdcnJ/1jlCaN7RKTNZexg2MRJAdhsru6GmgxUy5V",
	"d8PdcPF8OP9vAAAA////i3UgyDIAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
